DO TST_DIR
INKEY(0)
DO TST_DRV
INKEY(0)
DO TST_FILE
INKEY(0)
DO TST_PORTA
INKEY(0)
DO TST_MEM
INKEY(0)
DO TST_RND
INKEY(0)
DO TST_VER
RETURN

PROCEDURE TST_DIR
CLEAR
? "TESTE DE CRIACAO DE SUB-DIRETORIOS..."
? MKDIRCT("MASTER")
? "CONSEGUI 1 CRIACAO..."
? MKDIRCT("UTIL.000")
? "CONSEGUI 2 CRIACOES..."
? CHDIRCT("MASTER")
? "CONSEGUI ENTRAR NO SUB-DIRETORIO..."
RUN DIR
? CHDIRCT("..\UTIL.000")
RUN DIR
? "CONSEGUI ENTRAR NO OUTRO SUB-DIRETORIO..."
? CHDIRCT("..")
RUN DIR
? RMDIRCT("MASTER")
? "APAGUEI O SUB-DIRETORIO MASTER..."
? RMDIRCT("UTIL.000")
? "APAGUEI O SUB-DIRETORIO UTIL.000..."
? RMDIRCT("WESFSDF")
? "NAO CONSEGUI APAGAR O SUB-DIRETORIO WESFSDF..."
?
RETURN

PROCEDURE TST_DRV
CLEAR
? "ESTOU NO DRIVE -> ",GETDRIVE()
RUN DIR
INKEY(0)
SETDRIVE(1)
RUN DIR
? "ESTOU NO DRIVE -> ",GETDRIVE()
INKEY(0)
SETDRIVE(0)
RUN DIR
? "ESTOU NO DRIVE -> ",GETDRIVE()
INKEY(0)
SETDRIVE(2)
RETURN

PROCEDURE TST_FILE
CLEAR
? "TENTANDO ESCONDER O ARQUIVO TST.NDX..."
RUN DIR
X = CHGATTR("TST.NDX",0,0)
CHGATTR("TST.NDX",34,1)
? "FUNCIONOU..."
INKEY(0)
RUN DIR
? "ATRIBUTO ANTIGO -> ",X
CHGATTR("TST.NDX",X,1)
RETURN

PROCEDURE TST_PORTA
CLEAR
? "TENTANDO TESTE NAS PORTAS..."
? "PORTA 2F9 (INT ENABLE - COM2) (1)-> ",PORTIN(761)
? PORTOUT(761,1)
? "PORTA 2F9 (INT ENABLE - COM2) (32)-> ",PORTIN(761)
? "FUNCIONOU..."
RETURN

PROCEDURE TST_MEM
CLEAR
? "TENTANDO TESTE NA MEMORIA..."
? "PEEK B800:0000 -> ",MEMIN(-18432,0)
? "PEEK B800:0001 -> ",MEMIN(-18432,1)
MEMOUT(-18432,0,65)
MEMOUT(-18432,1,15)
*@ 0,0 SAY "W"
*@ 10,0
? "PEEK B800:0000 -> ",MEMIN(-18432,0)
? "PEEK B800:0001 -> ",MEMIN(-18432,1)
? "FUNCIONOU..."
RETURN

PROCEDURE TST_RND
CLEAR
FOR T = 1 TO 300
   ?? STR(RANDOMIC(100),2),"  "
NEXT
? "FUNCIONOU...."
RETURN

PROCEDURE TST_VER
CLEAR
? "TESTANDO A VERSAO DO DOS..."
? DOSVERSION()
?
? "FUNCIONOU..."
RETURN
